### PR TITLE
Lifecycle methods

### PR DESCRIPTION
**Pull request by Madumo**
Like we talked on issue #27, there is no real lifecycle hooks right now. I just added some:
- beforeRender
- afterRender
- beforeUpdate
- afterUpdate
- beforeRemove
- afterRemove

beforeUpdate and afterUpdate are both called with the update data.

### CODE REVIEW

**Comment by elfet** [comment]
Like this, but what is impact on perf? Calling a lot of noop? Also we need docs for this stuff.

**Comment by Madumo** [comment]
The jit normally see that the function call does nothing and remove it. It is actually faster than `if (thereIsAFunction) { callFunction(); }`.

[source (see part 3)](https://reaktor.com/blog/javascript-performance-fundamentals-make-bluebird-fast/)

**Comment by Madumo** [comment]
I just found out that this build sometime throw the `Can not insert child view into parent node. You need append your view first and then update.` error when inserting a comment node. I will look into that and come back with a fix and documentation.

**Comment by elfet** [comment]
Okay.

**Comment by Madumo** [comment]
Oh nevermind about the error, it was because of something else in my app, not because of that patch.

**Comment by antonmedv** [comment]
@Madumo sorry for delay) Now I'm working on v5 with full lifecycle events (see next branch)

**Pull request closed without merging**
